version: "2.1"
services:
   duckdns:
      image: ghcr.io/linuxserver/duckdns
      container_name: duckdns
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Madrid
         - TOKEN=8239f65e-656e-483c-ab41-881ad21649c5
         - LOG_FILE=false
      volumes:
         - /srv/dev-disk-by-uuid-7212C3C612C38E13/Docker/duckdns/appdata/config:/config
      restart: unless-stopped